# Generated by Django 4.0.5 on 2022-06-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='price',
            new_name='hotel_price',
        ),
    ]
