# Generated by Django 4.0.5 on 2022-06-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_price_hotels_hotel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_image',
            field=models.CharField(max_length=100),
        ),
    ]
