# Generated by Django 4.0.5 on 2022-06-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_hotels_hotel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotel_price',
            new_name='price',
        ),
    ]
